// // <auto-generated />
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using backend.Models;

// #nullable disable

// namespace backend.Migrations
// {
//     [DbContext(typeof(AppDbContext))]
//     [Migration("20211208174317_InsertDataInToTheTable")]
//     partial class InsertDataInToTheTable
//     {
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "6.0.0")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//             modelBuilder.Entity("backend.Models.Painting", b =>
//                 {
//                     b.Property<long>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("bigint");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

//                     b.Property<string>("Description")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Image")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Name")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

//                     b.ToTable("Paintings");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
